# Generated by Django 5.2.4 on 2025-07-10 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soundtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('emoji', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='SoundType',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
