# Generated by Django 5.2 on 2025-04-25 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('driving', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drivinghistory',
            name='avg_speed',
        ),
        migrations.RemoveField(
            model_name='drivinghistory',
            name='total_hard_brakes',
        ),
    ]
