# Generated by Django 5.1.7 on 2025-03-27 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('detections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audiodetection',
            name='sound_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.soundtype'),
        ),
        migrations.AlterField(
            model_name='visualdetection',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vehicletype'),
        ),
        migrations.DeleteModel(
            name='SoundType',
        ),
        migrations.DeleteModel(
            name='VehicleType',
        ),
    ]
