# Generated by Django 5.1.7 on 2025-03-27 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0002_alter_audiodetection_sound_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visualdetection',
            name='user',
        ),
        migrations.RemoveField(
            model_name='visualdetection',
            name='vehicle_type',
        ),
        migrations.DeleteModel(
            name='AudioDetection',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.DeleteModel(
            name='VisualDetection',
        ),
    ]
