# Generated by Django 5.2 on 2025-04-11 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0005_location_audiodetection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
