# Generated by Django 5.2 on 2025-04-26 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('detections', '0006_alter_location_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visualdetection',
            name='frequency',
            field=models.IntegerField(default=0),
        ),
    ]
